# Generated by Django 3.0.4 on 2020-05-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggyapp', '0012_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
