# Generated by Django 3.0.4 on 2020-05-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggyapp', '0013_auto_20200522_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='slug',
            new_name='info',
        ),
    ]
