# Generated by Django 3.0.4 on 2020-05-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggyapp', '0015_auto_20200522_0233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
