# Generated by Django 3.0.4 on 2020-05-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggyapp', '0016_delete_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
